services:

  auth:
    build: 
      context: ./apps/auth
      dockerfile: ./apps/auth/Dockerfile.dev
      target: development
    command: npm run start:dev auth
    env_file:
      - .env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
  reservations:
    build: 
      context: ./apps/reservations
      dockerfile: ./apps/reservations/Dockerfile.dev
      target: development
    command: npm run start:dev reservations
    env_file:
      - .env
    ports:
      - '3002:3002'
    volumes:
      - .:/usr/src/app

  payments:
    build: 
      context: ./apps/payments
      dockerfile: ./apps/payments/Dockerfile.dev
      target: development
    command: npm run start:dev payments
    env_file:
      - .env
    ports:
      - '3003:3003'
    volumes:
      - .:/usr/src/app
  mongo:
    image: mongo
